# Site
repository: noeski/noeski.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Noah Hilt
title: iOS Developer and Consultant
email: noeski@gmail.com
website: noeski.com

# Social links
# twitter_username: noeski
github_username:  noeski
linkedin_username: noah-hilt-1b68991a

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi 👋, my name is Noah, and I've been an iOS developer for the past nine years. I have a wide range of experience in every facet of app development, building from the ground up or refactoring ancient codebases. I am a strong believer in pragmatic programming and bringing the user experience to the forefront.

  My progression of programming languages is `C++` → `Objective-C` → `Swift`.

# Projects Section
projects_title: My Apps

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
more_title: More About Me
more_content: | # this will include new lines to allow paragraphs
  Well-versed in game engine architecture and `Unity`, I'm passionate about game design and game programming.

  Cooking (and eating) delicious food.

  ❤️ Miniature Australian Shepherds.

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude: [modern-resume-theme.gemspec, lib, Gemfile, Gemfile.lock]
